import numpy as np
x = np.array([30,50,10,20,30])
y = np.array([20,50,30,20,10])
print("array a")
print(x)
print("array b")
print(y)
print("a>b")
print(np.greater(x,y))
print("a>=b")
print(np.greater_equal(x,y))
print("a<b")
print(np.less(x,y))
print("a<=b")
print(np.less_equal(x,y))
